### ISSUE TITLE
Typ

### ISSUE THREAD

**Issue by mattsong1** [unixuser011/WindowsConfig#1]
Hello, 

It looks like there's a typo on line 635: Get-AppxPackage -AllUsers -Name **Microsft**.WindowsAlarms | Remove-AppxPackage -ErrorAction SilentlyContinue

**Comment by unixuser011** [comment]
shit, thanks, would never have seen that - might be releasing a new version
today which removes the specific package and instead removes everything
except packages required by the system

**Comment by unixuser011** [comment]
Fixed - thanks again
